name: CI - Validação de código

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js (para htmlhint)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Validar HTML
        run: |
          # Valida todos os arquivos HTML do repo (ignora node_modules por padrão)
          htmlhint "**/*.html"

      - name: Verificar links quebrados (Lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          # Verifica links em todos os HTML (e Markdown, se houver)
          args: --no-progress --verbose "**/*.html" "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

