name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # ou o nome da branch que você está usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # raiz do repositório ou pasta onde está o index.html

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
