name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch que você está usando

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # ou a pasta onde está o index.html

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
