name: CD — Deploy to GitHub Pages

on:
  # Roda na PR para aparecer o check de CD (só build)
  pull_request:
    branches: [principal, main]
  # Roda no push para principal/main (build + deploy de fato)
  push:
    branches: [principal, main]

# Permissões exigidas pelo Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita deploys concorrentes
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 1) CAIXINHA 1 — build (gera o artefato do site)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Se você tiver uma pasta específica, mude o path:
      # Ex.: path: ./site  ou ./public
      - name: Upload artifact (site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  # 2) CAIXINHA 2 — deploy (só roda em push para principal/main)
  deploy:
    # Só faz deploy quando for push para principal/main
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/principal')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
